version: '3.8'

services:

  sprowt-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: sprowtadmin
      POSTGRES_PASSWORD: sprowt
    ports:
      - "3001:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  sprowt-api:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./envs/.env.local
    ports:
      - "3000:8000"
    volumes:
      - .:/app
    depends_on:
      - sprowt-db
volumes:
  postgres_data:
    driver: local{}
