version: '3.8'

services:

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: wurk
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: wurk
    ports:
      - "3002:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8001"
    volumes:
      - .:/usr/src/app
    env_file:
      - ./envs/.env.local
    ports:
      - "3001:8001"
    depends_on:
      - db

volumes:
  postgres_data:
    driver: local
