# Generated by Django 5.0.4 on 2024-07-03 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='employees',
            new_name='employee',
        ),
    ]
